[project]
name = "project name"
libraries = ["work"]

[libraries]
work.files = [
	"top.vhd"
]

UNISIM.files = [
  "/tools/Xilinx/Vivado/2024.2/data/vhdl/src/unisims/unisim_VCOMP.vhd"
]
UNISIM.is_third_party = true

XPM.files = []
XPM.is_third_party = true


